_back-end/Kpei.PortalAK/ViewModels/UserRightSetting/IndexViewModel.cs
using System;

namespace Kpei.PortalAK.ViewModels.UserRightSetting {
    public class IndexViewModel {
        public bool IsKpei { get; set; }
        public Tuple<string, string>[] Modules { get; set; }
    }
}

_back-end/Kpei.PortalAK/Controllers/UserRightSettingController.cs
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Kpei.PortalAK.DataAccess.Core;
using Kpei.PortalAK.DataAccess.Forms.JqueryDataTable;
using Kpei.PortalAK.DataAccess.ModUserRight.Forms;
using Kpei.PortalAK.DataAccess.ModUserRight.Models;
using Kpei.PortalAK.DataAccess.ModUserRight.Repos;
using Kpei.PortalAK.DataAccess.Services;
using Kpei.PortalAK.DataAccess.UserIdentity;
using Kpei.PortalAK.ViewModels.UserRightSetting;

namespace Kpei.PortalAK.Controllers {
    [RoutePrefix("settings/user-right")]
    [Authorize]
    public class UserRightSettingController : Controller {
        private readonly ISysLogger _errlog;
        private readonly IUserRightRepository _repo;

        public UserRightSettingController(IUserRightRepository repo, ISysLogger errlog) {
            _repo = repo;
            _errlog = errlog;
        }

        /// <inheritdoc />
        protected override void OnAuthorization(AuthorizationContext filterContext) {
            var user = AppUser.CreateFromIdentity(User.Identity);
            var right = user?.GetRight();
            if (right?.ForModule[CoreModules.CORE_SYSTEM].KpeiAdmin != true) {
                filterContext.Result = new HttpStatusCodeResult(HttpStatusCode.Forbidden);
                return;
            }

            base.OnAuthorization(filterContext);
        }

        [HttpGet]
        [Route("")]
        public ActionResult Index(bool isKpei = true) {
            var mdl = new IndexViewModel {
                IsKpei = isKpei,
                Modules = CoreModules.IdAndNameTuples
            };
            return View(mdl);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("list")]
        public ActionResult List(UserRightDttRequestForm req) {
            var resp = new DttResponseForm();
            try {
                var result = _repo.GetMemberRights(req);

                resp.draw = req.draw;
                resp.recordsTotal = result.RecordsTotal;
                resp.recordsFiltered = result.RecordsFiltered;
                resp.data = result.Data.Select(x => new MemberUserInfoPerModule(x, req.ModuleId))
                    .Cast<object>().ToList();

                return Json(resp);
            } catch (Exception ex) {
                _errlog.LogError(ex);
                return Json(new DttResponseErrorForm(resp) {
                    error = $"{ex.Message} ({ex.GetType().Name})"
                });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("toggle")]
        public ActionResult Toggle(UserRightToggleForm mdl) {
            var result = _repo.ChangeRight(mdl.UserId, mdl.ModuleId, mdl.RightName, mdl.Check);
            return Json(new {
                HasRight = result
            });
        }
    }
}

_back-end/Kpei.PortalAK/Views/UserRightSetting/Index.cshtml
@using Kpei.PortalAK.ViewModels.UserRightSetting
@model IndexViewModel
@{
    ViewBag.Title = "Settings - Hak Akses User";
    Html.SelectedMenuTags().AddRange(new[] {"setting", "user-right-setting"});
}

<ul class="nav nav-tabs">
    <li class="@(Model.IsKpei ? "active" : "")">
        <a href="@Url.Action("Index", "UserRightSetting", new {area = "", isKpei = true})"> KPEI </a>
    </li>
    <li class="@(!Model.IsKpei ? "active" : "")">
        <a href="@Url.Action("Index", "UserRightSetting", new {area = "", isKpei = false})"> Non KPEI </a>
    </li>
</ul>
<div class="tab-content">
    <div class="tab-pane fade active in">
        <div class="row">
            <div class="col-md-4">
                <label>Pilih Modul:</label>
                <select id="module-selector" class="form-control">
                    @foreach (var mod in Model.Modules) {
                        <option value="@mod.Item1">@mod.Item2</option>
                    }
                </select>
            </div>
            <div class="col-xs-12">
                <hr/>
                <table id="master-table" class="table table-condensed table-bordered table-hover">
                    <thead></thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@using (Html.Section("script-page-level")) {
    <script src="~/assets/custom/vue-components/user-right-toggler.js" type="text/javascript"></script>
    <script id="user-right-toggler-container-template" type="text/x-handlebars-template">
        <div class="user-right-toggler" data-module-id="{{moduleId}}"
             data-right-name="{{rightName}}" data-has-right="{{hasRight}}"
             data-user-id="{{userId}}"></div>
    </script>
    <script id="user-right-toggler-vue-template" type="text/x-template">
        <user-right-toggler :checked="checked" :is-loading="isLoading" @@toggleClicked="toggled"></user-right-toggler>
    </script>
    <script type="text/javascript">
        $(function() {
            var togglerRendererFunc = function(rightName) {
                return function(data, type, row, meta) {
                    var tpl = Handlebars.compile($('#user-right-toggler-container-template').html());
                    var pars = {
                        userId: row.Id,
                        moduleId: $('#module-selector').val(),
                        rightName: rightName,
                        hasRight: data ? 'true' : 'false'
                    }
                    return tpl(pars);
                };
            }

            var cols = [
                {
                    name: 'UserName',
                    data: 'UserName',
                    title: 'Username',
                    searchable: true,
                    orderable: true
                },
                {
                    name: 'CompanyCode',
                    data: 'CompanyCode',
                    title: 'Kode AK',
                    searchable: true,
                    orderable: true
                },
                {
                    name: 'Right.KpeiApprover',
                    data: 'Right.KpeiApprover',
                    title: 'Approver',
                    searchable: false,
                    orderable: false,
                    visible: @(Model.IsKpei ? "true" : "false"),
                    render: togglerRendererFunc('KpeiApprover')
                },
                {
                    name: 'Right.KpeiViewer',
                    data: 'Right.KpeiViewer',
                    title: 'Viewer',
                    searchable: false,
                    orderable: false,
                    visible: @(Model.IsKpei ? "true" : "false"),
                    render: togglerRendererFunc('KpeiViewer')
                },
                {
                    name: 'Right.KpeiModifier',
                    data: 'Right.KpeiModifier',
                    title: 'Modifier',
                    searchable: false,
                    orderable: false,
                    visible: @(Model.IsKpei ? "true" : "false"),
                    render: togglerRendererFunc('KpeiModifier')
                },
                {
                    name: 'Right.KpeiAdmin',
                    data: 'Right.KpeiAdmin',
                    title: 'Admin',
                    searchable: false,
                    orderable: false,
                    visible: @(Model.IsKpei ? "true" : "false"),
                    render: togglerRendererFunc('KpeiAdmin')
                },
                {
                    name: 'Right.NonKpeiViewer',
                    data: 'Right.NonKpeiViewer',
                    title: 'Viewer',
                    searchable: false,
                    orderable: false,
                    visible: @(Model.IsKpei ? "false" : "true"),
                    render: togglerRendererFunc('NonKpeiViewer')
                },
                {
                    name: 'Right.NonKpeiModifier',
                    data: 'Right.NonKpeiModifier',
                    title: 'Modifier',
                    searchable: false,
                    orderable: false,
                    visible: @(Model.IsKpei ? "false" : "true"),
                    render: togglerRendererFunc('NonKpeiModifier')
                },
                {
                    name: 'Right.NonKpeiViewerAsKpei',
                    data: 'Right.NonKpeiViewerAsKpei',
                    title: 'View as KPEI',
                    searchable: false,
                    orderable: false,
                    visible: @(Model.IsKpei ? "false" : "true"),
                    render: togglerRendererFunc('NonKpeiViewerAsKpei')
                }
            ];

            var masterTable = PortalAK.InitDtt('#master-table',
                '@Url.Action("List", "UserRightSetting")',
                cols,
                [
                    [1, 'asc']
                ],
                function(e, stg, dat) {
                    dat.IsKpei = @(Model.IsKpei ? "true" : "false");
                    dat.ModuleId = $('#module-selector').val();
                });

            masterTable.on('draw.dt',
                function() {
                    _.forEach($('#master-table').find('div.user-right-toggler'),
                        function(toggler) {
                            var $tog = $(toggler);

                            var initChecked = $tog.attr('data-has-right') === 'true';
                            var moduleId = $tog.attr('data-module-id');
                            var rightName = $tog.attr('data-right-name');
                            var userId = $tog.attr('data-user-id');

                            PortalAK.LoadVue({
                                el: toggler,
                                template: '#user-right-toggler-vue-template',
                                data: {
                                    checked: initChecked,
                                    isLoading: false
                                },
                                methods: {
                                    toggled: function(check) {
                                        var self = this;

                                        var postData = {
                                            UserId: userId,
                                            ModuleId: moduleId,
                                            RightName: rightName,
                                            Check: check,
                                            __RequestVerificationToken: PortalAK.AntiForgeryToken
                                        };

                                        $.post('@Url.Action("Toggle", "UserRightSetting", new {area = ""})', postData)
                                            .done(function(res) {
                                                self.checked = res.HasRight;
                                            })
                                            .always(function() {
                                                self.isLoading = false;
                                            });
                                    }
                                }
                            });
                        });
                });

            $('#module-selector').on('change',
                function() {
                    masterTable.ajax.reload();
                });
        });
    </script>
}