_back-end/Kpei.PortalAK/ViewModels/AdministrasiKeanggotaan/ListRequestViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Kpei.PortalAK.DataAccess.ModAdministrasiKeanggotaan.Models;
using Kpei.PortalAK.DataAccess.ModSettings.Forms;
using Kpei.PortalAK.DataAccess.Services;
using Kpei.PortalAK.DataAccess.UserIdentity;

namespace Kpei.PortalAK.ViewModels.AdministrasiKeanggotaan
{
    public class ListRequestViewModel
    {
        private IEnumerable<KpeiCompany> _companies;

        public AppUser User { get; set; }
        public GlobalSettingForm GlobalSetting { get; set; }

        public IEnumerable<KpeiCompany> Companies {
            get { return _companies ?? new KpeiCompany[0]; }
            set { _companies = value; }
        }

        public IEnumerable<AdministrasiKeanggotaanRequestStatus> Statuses = AdministrasiKeanggotaanRequestStatus.All().ToList();
    }
}

_back-end/Kpei.PortalAK/ViewModels/DataAknp/CreateHistoryViewModel.cs
using Kpei.PortalAK.DataAccess.ModDataAknp.Forms;
using Kpei.PortalAK.DataAccess.ModDataAknp.Models;
using Kpei.PortalAK.DataAccess.ModSettings.Forms;
using Kpei.PortalAK.DataAccess.Services;
using Kpei.PortalAK.DataAccess.UserIdentity;

namespace Kpei.PortalAK.ViewModels.DataAknp {
    public class CreateHistoryViewModel {
        private KpeiCompany[] _companies;
        public BaseAknpDriver Driver { get; set; }

        public GlobalSettingForm GlobalSetting { get; set; }

        public AppUser User { get; set; }
        public BaseAknpForm Form { get; set; }
        public string KodeAk { get; set; }

        public KpeiCompany[] Companies {
            get { return _companies ?? new KpeiCompany[0]; }
            set { _companies = value; }
        }
    }
}

_back-end/Kpei.PortalAK/ViewModels/DataAknp/DetailKpeiViewModel.cs
using Kpei.PortalAK.DataAccess.ModDataAknp.Models;
using Kpei.PortalAK.DataAccess.Services;
using Kpei.PortalAK.DataAccess.UserIdentity;

namespace Kpei.PortalAK.ViewModels.DataAknp {
    public class DetailKpeiViewModel {
        private KpeiCompany[] _companies;

        public BaseAknpDriver Driver { get; set; }
        public AppUser User { get; set; }
        public string KodeAk { get; set; }
        public string ViewMode { get; set; }

        public KpeiCompany[] Companies {
            get { return _companies ?? new KpeiCompany[0]; }
            set { _companies = value; }
        }
    }
}

_back-end/Kpei.PortalAK/ViewModels/DataAknp/DetailNonKpeiViewModel.cs
using Kpei.PortalAK.DataAccess.ModDataAknp.Models;
using Kpei.PortalAK.DataAccess.UserIdentity;

namespace Kpei.PortalAK.ViewModels.DataAknp {
    public class DetailNonKpeiViewModel {
        public BaseAknpDriver Driver { get; set; }
        public AppUser User { get; set; }
        public string KodeAk { get; set; }
    }

}

_back-end/Kpei.PortalAK/ViewModels/DataAknp/DetailRenderViewModel.cs
using Kpei.PortalAK.DataAccess.DbModels;
using Kpei.PortalAK.DataAccess.ModDataAknp.Models;
using Kpei.PortalAK.DataAccess.UserIdentity;

namespace Kpei.PortalAK.ViewModels.DataAknp {
    public class DetailRenderViewModel {
        public BaseAknpDriver Driver { get; set; }
        public AppUser User { get; set; }
        public BaseAknpData Data { get; set; }
    }
}

_back-end/Kpei.PortalAK/ViewModels/DataAknp/FieldViewModel.cs
using Kpei.PortalAK.DataAccess.DbModels;
using Kpei.PortalAK.DataAccess.ModDataAknp.Models;
using Kpei.PortalAK.DataAccess.UserIdentity;
using Kpei.PortalAK.Features.DataAknpViewSystem;

namespace Kpei.PortalAK.ViewModels.DataAknp {
    public class FieldViewModel {
        public object PropertyValue { get; set; }
        public BaseAknpData Data { get; set; }
        public DataAknpViewDefinition ViewDefinition { get; set; }
        public BaseAknpDriver Driver { get; set; }
        public AppUser User { get; set; }
    }
}

_back-end/Kpei.PortalAK/ViewModels/DataAknp/FormFieldViewModel.cs
using Kpei.PortalAK.DataAccess.ModDataAknp.Forms;
using Kpei.PortalAK.DataAccess.ModDataAknp.Models;
using Kpei.PortalAK.DataAccess.UserIdentity;
using Kpei.PortalAK.Features.DataAknpViewSystem;

namespace Kpei.PortalAK.ViewModels.DataAknp {
    public class FormFieldViewModel {
        public object PropertyValue { get; set; }
        public BaseAknpForm Form { get; set; }
        public DataAknpViewDefinition ViewDefinition { get; set; }
        public BaseAknpDriver Driver { get; set; }
        public AppUser User { get; set; }
        public string KodeAk { get; set; }
    }
}

_back-end/Kpei.PortalAK/ViewModels/DataAknp/FormRenderViewModel.cs
using Kpei.PortalAK.DataAccess.ModDataAknp.Forms;
using Kpei.PortalAK.DataAccess.ModDataAknp.Models;
using Kpei.PortalAK.DataAccess.ModSettings.Forms;
using Kpei.PortalAK.DataAccess.Services;
using Kpei.PortalAK.DataAccess.UserIdentity;

namespace Kpei.PortalAK.ViewModels.DataAknp {
    public class FormRenderViewModel {
        public BaseAknpDriver Driver { get; set; }

        public GlobalSettingForm GlobalSetting { get; set; }

        public KpeiCompany[] Companies { get; set; }
        public AppUser User { get; set; }
        public BaseAknpForm Form { get; set; }
    }
}

_back-end/Kpei.PortalAK/ViewModels/DataAknp/ListGlobalRequestViewModel.cs
using Kpei.PortalAK.DataAccess.ModDataAknp.Models;
using Kpei.PortalAK.DataAccess.Services;
using Kpei.PortalAK.DataAccess.UserIdentity;

namespace Kpei.PortalAK.ViewModels.DataAknp {
    public class ListRequestViewModel {
        private KpeiCompany[] _companies;
        private DataAknpRequestStatus[] _requestStatuses;
        public AppUser User { get; set; }
        public BaseAknpDriver Driver { get; set; }
        public DataAknpRequestStatus[] RequestStatuses {
            get { return _requestStatuses ?? new DataAknpRequestStatus[0]; }
            set { _requestStatuses = value; }
        }
        public KpeiCompany[] Companies {
            get { return _companies ?? new KpeiCompany[0]; }
            set { _companies = value; }
        }
    }
}

_back-end/Kpei.PortalAK/ViewModels/DataAknp/ListHistoryViewModel.cs
using Kpei.PortalAK.DataAccess.ModDataAknp.Models;
using Kpei.PortalAK.DataAccess.Services;
using Kpei.PortalAK.DataAccess.UserIdentity;

namespace Kpei.PortalAK.ViewModels.DataAknp {
    public class ListHistoryViewModel {
        private KpeiCompany[] _companies;
        private DataAknpRequestStatus[] _requestStatuses;
        public AppUser User { get; set; }
        public BaseAknpDriver Driver { get; set; }
        public DataAknpRequestStatus[] RequestStatuses {
            get { return _requestStatuses ?? new DataAknpRequestStatus[0]; }
            set { _requestStatuses = value; }
        }
        public KpeiCompany[] Companies {
            get { return _companies ?? new KpeiCompany[0]; }
            set { _companies = value; }
        }
    }
}

_back-end/Kpei.PortalAK/ViewModels/DataAknp/ListRequestViewModel.cs
using Kpei.PortalAK.DataAccess.ModDataAknp.Models;
using Kpei.PortalAK.DataAccess.Services;
using Kpei.PortalAK.DataAccess.UserIdentity;

namespace Kpei.PortalAK.ViewModels.DataAknp {
    public class ListGlobalRequestViewModel {
        private KpeiCompany[] _companies;
        private DataAknpRequestStatus[] _requestStatuses;
        public AppUser User { get; set; }
        public DataAknpRequestStatus[] RequestStatuses {
            get { return _requestStatuses ?? new DataAknpRequestStatus[0]; }
            set { _requestStatuses = value; }
        }
        public KpeiCompany[] Companies {
            get { return _companies ?? new KpeiCompany[0]; }
            set { _companies = value; }
        }
        private DataAknpDefinition[] _dataDefinitions;
        public DataAknpDefinition[] DataDefinitions {
            get { return _dataDefinitions ?? new DataAknpDefinition[0]; }
            set { _dataDefinitions = value; }
        }
    }
}

_back-end/Kpei.PortalAK/Controllers/DataAknpController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Net;
using System.Transactions;
using System.Web.Mvc;
using JrzAsp.Lib.DirectViewRenderer;
using Kpei.PortalAK.DataAccess.Core;
using Kpei.PortalAK.DataAccess.DbModels;
using Kpei.PortalAK.DataAccess.Forms.JqueryDataTable;
using Kpei.PortalAK.DataAccess.ModDataAknp.Attributes;
using Kpei.PortalAK.DataAccess.ModDataAknp.Forms;
using Kpei.PortalAK.DataAccess.ModDataAknp.Forms.ChangeRequest;
using Kpei.PortalAK.DataAccess.ModDataAknp.Models;
using Kpei.PortalAK.DataAccess.ModDataAknp.Repos;
using Kpei.PortalAK.DataAccess.ModDataAknp.Services;
using Kpei.PortalAK.DataAccess.ModSettings.Forms;
using Kpei.PortalAK.DataAccess.ModSettings.Repos;
using Kpei.PortalAK.DataAccess.Services;
using Kpei.PortalAK.DataAccess.UserIdentity;
using Kpei.PortalAK.Features;
using Kpei.PortalAK.Features.DataAknpViewSystem;
using Kpei.PortalAK.Features.Pdf;
using Kpei.PortalAK.ViewModels.DataAknp;
using Kpei.PortalAK.DataAccess.ModDataAknp.Drivers;
using System.Web.Routing;

namespace Kpei.PortalAK.Controllers {
    [Authorize]
    [RoutePrefix("aknp")]
    public class DataAknpController : Controller {
        private readonly IKpeiCompanyService _compSvc;
        private readonly IDataAknpDriverStore _dataAknpDrvs;
        private readonly IDataAknpRepository _dataAknpRepo;
        private readonly ISettingRepository _stg;
        private readonly IUserActionLogService _ulog;
        private readonly IPdfConverter _pdfConvert;
        private readonly IUserService _usersvc;

        public DataAknpController(IDataAknpRepository repo, IDataAknpDriverStore dataAknpDrvs,
            IKpeiCompanyService compSvc, IUserActionLogService ulog, ISettingRepository stg, IPdfConverter pdfConvert, IUserService usersvc) {
            _dataAknpRepo = repo;
            _dataAknpDrvs = dataAknpDrvs;
            _compSvc = compSvc;
            _ulog = ulog;
            _stg = stg;
            _usersvc = usersvc;
            _pdfConvert = pdfConvert;
        }

        private AppUser AppUser => User.Identity.GetAppUser();
        private GlobalSettingForm GlobalSetting => _stg.GlobalSetting();

        [Route("profil/{kodeAk?}")]
        [HttpGet]
        public ActionResult Profile(string kodeAk = null) {
            if (!AppUser.NonKpeiViewerRightFor(CoreModules.DATA_AK_PARTISIPAN) &&
                !AppUser.KpeiViewerRightFor(CoreModules.DATA_AK_PARTISIPAN) &&
                !AppUser.NonKpeiViewerAsKpei(CoreModules.DATA_AK_PARTISIPAN)) {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }

            if (AppUser.NonKpeiViewerRightFor(CoreModules.DATA_AK_PARTISIPAN) && 
                !AppUser.NonKpeiViewerAsKpei(CoreModules.DATA_AK_PARTISIPAN) && 
                kodeAk != AppUser.KpeiCompanyCode) {
                kodeAk = AppUser.KpeiCompanyCode;
            }
            var guestCode = _stg.GlobalSetting().GuestAknpCode;

            return View(new ProfileViewModel {
                User = AppUser,
                DriverStore = _dataAknpDrvs,
                KodeAk = kodeAk,
                Companies = _compSvc.AllKpeiCompanies().Where(e => e.Code != guestCode).ToArray(),
            });
        }

        [Route("profil-pdf/{kodeAk}")]
        [HttpGet]
        public ActionResult ProfilePdf(string kodeAk) {
            if (!AppUser.NonKpeiViewerRightFor(CoreModules.DATA_AK_PARTISIPAN) &&
                !AppUser.KpeiViewerRightFor(CoreModules.DATA_AK_PARTISIPAN) &&
                !AppUser.NonKpeiViewerAsKpei(CoreModules.DATA_AK_PARTISIPAN)) {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }

            if (!AppUser.NonKpeiViewerAsKpei(CoreModules.DATA_AK_PARTISIPAN) && 
                AppUser.NonKpeiViewerRightFor(CoreModules.DATA_AK_PARTISIPAN) && 
                kodeAk != AppUser.KpeiCompanyCode) {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }

            var comps = _compSvc.AllKpeiCompanies();
            var comp = comps.FirstOrDefault(x => x.Code == kodeAk);
            if (comp == null) {
                return HttpNotFound();
            }

            var profile = new AknpProfileDisplay();
            profile.Populate(kodeAk, _dataAknpDrvs);

            var mdl = new ProfilePdfTemplateViewModel {
                KodeAk = kodeAk,
                User = AppUser,
                Companies = comps,
                ProfileData = profile
            };

            var html = this.RenderViewToString("~/Views/DataAknp/_ProfilePdfTemplate.cshtml", mdl, true);
            var pdf = _pdfConvert.ConvertFromHtmlToPdf(html, new[] {"~/assets/custom/css/profile-pdf-template.css"});

            return File(pdf, "application/pdf", $"Ringkasan Profil - {comp.Code} - {comp.Name}.{DateTime.Now:yyyyMMdd.HHmmss}.pdf");
        }

        [Route("{dataSlug}/remove-draft/{id}")]
        [HttpGet]
        public ActionResult RemoveDraft(string dataSlug, string id = null) {
            var drv = _dataAknpDrvs.LoadDrivers().FirstOrDefault(x => x.IsMatchDataSlug(dataSlug));
            if (drv == null) return HttpNotFound();
            drv.RemoveDraft(id);
            if (AppUser.IsGuestAknp)
            {
                return RedirectToAction("RequestChange", new {dataSlug});
            }
            return RedirectToAction("Detail", new {dataSlug});
        }

        [Route("{dataSlug}")]
        [HttpGet]
        public ActionResult Detail(string dataSlug, string kodeAk = null, string viewMode = null) {
            var drv = _dataAknpDrvs.LoadDrivers().FirstOrDefault(x => x.IsMatchDataSlug(dataSlug));
            if (drv == null) return HttpNotFound();

            if (drv.IsRegistrationData) {
                return RedirectToAction("ListRequest", new {dataSlug});
            }

            if (drv.EnabledOnlyForKpei && 
                !AppUser.KpeiViewerRightFor(CoreModules.DATA_AK_PARTISIPAN) && 
                !AppUser.NonKpeiViewerAsKpei(CoreModules.DATA_AK_PARTISIPAN)) {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }

            var companies = _compSvc.AllKpeiCompanies();

            companies = companies.Where(x => x.Code != GlobalSetting.GuestAknpCode).ToArray();

            if (string.IsNullOrWhiteSpace(viewMode)) {
                viewMode = "table";
            }
            
            if (AppUser.KpeiViewerRightFor(CoreModules.DATA_AK_PARTISIPAN) ||
                AppUser.NonKpeiViewerAsKpei(CoreModules.DATA_AK_PARTISIPAN)) {
                return View("DetailKpei", new DetailKpeiViewModel {
                    KodeAk = kodeAk,
                    ViewMode = viewMode,
                    User = AppUser,
                    Companies = companies,
                    Driver = drv
                });
            }

            if (AppUser.NonKpeiViewerRightFor(CoreModules.DATA_AK_PARTISIPAN)) {
                if (kodeAk != null) {
                    return RedirectToAction("Detail", new {dataSlug = drv.DataSlug, kodeAk = ""});
                }

                return View("DetailNonKpei", new DetailNonKpeiViewModel {
                    KodeAk = AppUser.KpeiCompanyCode,
                    User = AppUser,
                    Driver = drv
                });
            }

            return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
        }

        [Route("{dataSlug}/detail-dtt")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DetailDtt(string dataSlug, BaseAknpDttRequestForm req) {
            var drv = _dataAknpDrvs.LoadDrivers().FirstOrDefault(x => x.IsMatchDataSlug(dataSlug));
            if (drv == null) return HttpNotFound();

            //if (!AppUser.KpeiViewerRightFor(CoreModules.DATA_AK_PARTISIPAN) && !AppUser.NonKpeiViewerAsKpei(CoreModules.DATA_AK_PARTISIPAN)) {
            //    return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            //}

            var comps = _compSvc.AllKpeiCompanies();
            var allLatest = comps.Select(x => drv.GetLatestActiveData(x.Code)).Where(x => x != null)
                .ToArray().AsQueryable();
            var data = drv.List(req, allLatest);
            var pag = new PaginatedResult<BaseAknpData>();
            pag.Initialize(data.All, data.Filtered, req.start, req.length);

            var res = new DttResponseForm {
                draw = req.draw,
                recordsTotal = pag.RecordsTotal,
                recordsFiltered = pag.RecordsFiltered,
                data = pag.Data.Select(x => MakeDetailDttItem(drv, x)).Cast<object>().ToList()
            };
            return Json(res);
        }

        [Route("{dataSlug}/request")]
        [HttpGet]
        public ActionResult RequestChange(string dataSlug) {
            var drv = _dataAknpDrvs.LoadDrivers().FirstOrDefault(x => x.IsMatchDataSlug(dataSlug));
            if (drv == null) return HttpNotFound();

            if (drv.IsRegistrationData && !AppUser.IsGuestAknp ||
                !drv.IsRegistrationData && !AppUser.NonKpeiModifierRightFor(CoreModules.DATA_AK_PARTISIPAN)) {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }
            var form = drv.InitDraftForm(AppUser.KpeiCompanyCode, AppUser.Id);

            var mdl = new RequestChangeViewModel {
                User = AppUser,
                Driver = drv,
                GlobalSetting = GlobalSetting,
                Companies = _compSvc.AllKpeiCompanies(),
                Form = form
            };

            if (drv.DataSlug != DataRegistrasiAknpDriver.SLUG && string.IsNullOrWhiteSpace(form.Id))
            {
                mdl.Form = drv.InitForm(AppUser.KpeiCompanyCode);
                mdl.Form.Id = null;
            }

            if (mdl.Form.Draft && !string.IsNullOrWhiteSpace(mdl.Form.UserDraft))
            {

_back-end/Kpei.PortalAK/Views/DataAknp/CreateHistory.cshtml
@using Kpei.PortalAK.ViewModels.DataAknp
@model CreateHistoryViewModel
@{
    var drv = Model.Driver;
    var usr = Model.User;
    var fm = Model.Form;
    var kodeAk = Model.KodeAk;

    ViewBag.Title = $"Data Anggota Kliring & Partisipan - {drv.DataTitle} - Input Baru";
    Html.SelectedMenuTags().AddRange(new[] { "data-aknp", drv.RequiresAkteForChange ? "dengan-akte" : (drv.EnabledOnlyForKpei ? "stat-perj" : "dengan-surat"), drv.DataSlug });
}

<form method="post" class="form form-horizontal">
    @Html.MetronicValidationSummary()

    @Html.AntiForgeryToken()

    <div class="form-body">
        @{
            var mdl = new FormRenderViewModel
            {
                User = usr,
                GlobalSetting = Model.GlobalSetting,
                Driver = drv,
                Form = fm,
                Companies = Model.Companies
            };
        }
        @Html.PartialFor(mdl, "_FormRender", x => x)
    </div>

    <div class="form-actions">
        <div class="row">
            <div class="col-md-offset-3 col-md-8">
                <button type="button" class="btn red form-submit-button">
                    Submit
                </button>

                <button type="button" class="btn btn-warning form-draft-button">
                    Save as Draft
                </button>
                <a href="@Url.Action("ListHistory", new {dataSlug = drv.DataSlug})" class="btn btn-default">
                    Cancel
                </a>
            </div>
        </div>
    </div>

</form>
@using (Html.Section("script"))
{
    <script type="text/javascript">
        $(function () {
            var kodeAkSel = $('.kode-ak-selector-container select');
            if (kodeAkSel.val() != "@(Model.GlobalSetting?.GuestAknpCode ?? "")") {
                kodeAkSel.on('change', function () {
                    var me = $(this);
                    var urlTpl =
                        '@Url.Action("CreateHistory", new {dataSlug = drv.DataSlug, kodeAk = "11000011"})';
                    var url = urlTpl.replace('11000011', me.val());
                    if (me.val() != "") {
                        window.location = url;
                    }
                });
            }
        });
    </script>
}

_back-end/Kpei.PortalAK/Views/DataAknp/DetailNonKpei.cshtml
@using Kpei.PortalAK.DataAccess.Core
@using Kpei.PortalAK.ViewModels.DataAknp
@model DetailNonKpeiViewModel
@{
    var drv = Model.Driver;
    var usr = Model.User;
    ViewBag.Title = $"Data Anggota Kliring & Partisipan - {drv.DataTitle} - Detail";
    Html.SelectedMenuTags().AddRange(new[] {"data-aknp", drv.RequiresAkteForChange ? "dengan-akte" : (drv.EnabledOnlyForKpei ? "stat-perj" : "dengan-surat"), drv.DataSlug});
}
<div class="row">
    <div class="col-xs-12">
        <div class="text-right">
            @if (usr.NonKpeiModifierRightFor(CoreModules.DATA_AK_PARTISIPAN)) {
                <a href="@Url.Action("RequestChange", new {dataSlug = drv.DataSlug})" class="btn red">
                    Request Perubahan @drv.DataTitle
                </a>
            }
        </div>
        <ul class="nav nav-tabs">
            <li class="active">
                <a href="@Url.Action("Detail", new {dataSlug = drv.DataSlug})">
                    Detail
                </a>
            </li>
            <li class="">
                <a href="@Url.Action("ListRequest", new {dataSlug = drv.DataSlug})">
                    Request
                </a>
            </li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane fade active in">
                <div class="form form-horizontal">
                    <div class="form-body">
                        @{
                            var latestData = drv.GetLatestActiveData(usr.KpeiCompanyCode);
                            var mdl = new DetailRenderViewModel {
                                User = usr,
                                Driver = drv,
                                Data = latestData
                            };
                        }
                        @Html.PartialFor(mdl, "_DetailRender", x => x)
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

_back-end/Kpei.PortalAK/Views/DataAknp/Profile.cshtml
@using Kpei.PortalAK.DataAccess.ModDataAknp.Models
@using Kpei.PortalAK.ViewModels.DataAknp
@using Kpei.PortalAK.DataAccess.Core
@model ProfileViewModel
@{
    ViewBag.Title = $"Data Anggota Kliring & Partisipan - Ringkasan";
    Html.SelectedMenuTags().AddRange(new[] { "data-aknp-profile" });

    var usr = Model.User;
    var store = Model.DriverStore;
    var kodeak = Model.KodeAk;

    var profileDisplay = new AknpProfileDisplay();
    profileDisplay.Populate(kodeak, store);
}

<div class="row">
        @if (usr.IsKpei || usr.NonKpeiViewerAsKpei(CoreModules.DATA_AK_PARTISIPAN)) {
            <div class="col-md-6">
                <label>Kode AK:</label>
                <select class="form-control" name="" onchange="window.location.replace($(this).val())">
                    <option value="">-Pilih-</option>
                    @foreach (var mod in Model.Companies) {
                        <option value="@Url.Action("Profile", new {kodeAk = mod.Code})"
                                @(kodeak == mod.Code ? "selected" : "")>@mod.Code / @mod.Name</option>
                    }
                </select>
            </div>
        }
    @if (!string.IsNullOrWhiteSpace(kodeak)) {
        <div class="col-md-@(usr.IsKpei ? 6 : 12) text-right">
            <a download href="@Url.Action("ProfilePdf", new {kodeAk = kodeak})" class="btn btn red">
                PDF <i class="fa fa-download"></i>
            </a>
        </div>
    }
</div>
<div class="row">
    <div class="col-xs-12 form-horizontal">
        <hr/>
        @if (string.IsNullOrWhiteSpace(kodeak)) {
            <p>
                Pilih kode AK untuk melihat ringkasan datanya.
            </p>
        } else {
            var mdl = new DetailRenderViewModel {
                User = usr,
                Driver = null,
                Data = profileDisplay
            };
            @Html.PartialFor(mdl, "_DetailRender", x => x)
        }
    </div>
</div>

_back-end/Kpei.PortalAK/Views/DataAknp/RequestChangeLog.cshtml
@using Kpei.PortalAK.DataAccess.DbModels
@using Kpei.PortalAK.ViewModels.DataAknp
@model RequestChangeLogViewModel
@{
    var drv = Model.Driver;
    var usr = Model.User;
    var data = Model.Data;

    ViewBag.Title = $"Data Anggota Kliring & Partisipan - {drv.DataTitle} - Log Request";
    Html.SelectedMenuTags().AddRange(new[] {"data-aknp", drv.RequiresAkteForChange ? "dengan-akte" : (drv.EnabledOnlyForKpei ? "stat-perj" : "dengan-surat"), drv.DataSlug});
}
<div class="row">
    <div class="col-xs-12">
        <ul class="nav nav-tabs">
            <li class="">
                <a href="@Url.Action("RequestChangeDetail", new {dataSlug = drv.DataSlug, id = data.Id})">
                    Data @drv.DataTitle
                </a>
            </li>
            <li class="active">
                <a href="@Url.Action("RequestChangeLog", new {dataSlug = drv.DataSlug, id = data.Id})">
                    Log
                </a>
            </li>
        </ul>
        <table id="master-table" class="table table-condensed table-bordered table-hover">
            <thead></thead>
            <tbody></tbody>
        </table>
    </div>
</div>
@using (Html.Section("script-page-level")) {
    <script type="text/javascript">
        $(function() {
            var $masterTable = $('#master-table');

            var cols = [
                {
                    name: '@(nameof(UserActionLog.CreatedUtc))',
                    data: 'WaktuPerubahan',
                    title: 'Waktu Perubahan',
                    searchable: false,
                    orderable: true
                },
                {
                    name: '@(nameof(UserActionLog.UserName))',
                    data: 'DibuatOleh',
                    title: 'Dibuat Oleh',
                    searchable: true,
                    orderable: true
                },
                {
                    name: '@(nameof(UserActionLog.Message))',
                    data: 'Aktivitas',
                    title: 'Aktivitas',
                    searchable: true,
                    orderable: true
                }
            ];

            var masterTable = PortalAK.InitDtt('#master-table',
                '@Url.Action("RequestChangeLogDtt", "DataAknp")',
                cols,
                [
                    [1, 'desc']
                ],
                function(e, stg, dat) {
                    // no modding
                });
        });
    </script>
}